package four.complete.ui.frames;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.UIManager;

/**
 *
 * @author Keshan De Silva
 */
public class MainMenu extends javax.swing.JFrame
{

    private final GameServerUI gameServerUI = new GameServerUI();
    private final GameClientUI gameClientUI = new GameClientUI();
    
    public MainMenu()
    {
        try
        {
            UIManager.setLookAndFeel(UIManager.getSystemLookAndFeelClassName());
        }
        catch (Exception ex){}
        initComponents();
        
        gameServerUI.setBackButtonActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent ae)
            {
                setSize(gameServerUI.getSize());
                setLocation(gameServerUI.getLocation());
                setVisible(true);
            }
        });
        
        gameClientUI.setBackButtonActionListener(new ActionListener()
        {
            @Override
            public void actionPerformed(ActionEvent ae)
            {
                setSize(gameClientUI.getSize());
                setLocation(gameClientUI.getLocation());
                setVisible(true);
            }
        });
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents()
    {

        lblMainImage = new javax.swing.JLabel();
        lblStartGameServer = new javax.swing.JLabel();
        lblExit = new javax.swing.JLabel();
        lblConnect = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Four-Complete");
        setMinimumSize(new java.awt.Dimension(414, 367));
        setPreferredSize(new java.awt.Dimension(414, 367));
        setResizable(false);

        lblMainImage.setIcon(new javax.swing.ImageIcon(getClass().getResource("/four/complete/resources/back.jpg"))); // NOI18N
        lblMainImage.setOpaque(true);

        lblStartGameServer.setBackground(new java.awt.Color(255, 0, 0));
        lblStartGameServer.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblStartGameServer.setForeground(new java.awt.Color(255, 255, 255));
        lblStartGameServer.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblStartGameServer.setText("Start Game Server");
        lblStartGameServer.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblStartGameServer.setMaximumSize(new java.awt.Dimension(130, 25));
        lblStartGameServer.setMinimumSize(new java.awt.Dimension(130, 25));
        lblStartGameServer.setOpaque(true);
        lblStartGameServer.setPreferredSize(new java.awt.Dimension(130, 25));
        lblStartGameServer.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblStartGameServerMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                lblStartGameServerMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                lblStartGameServerMouseExited(evt);
            }
        });

        lblExit.setBackground(new java.awt.Color(51, 153, 0));
        lblExit.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblExit.setForeground(new java.awt.Color(255, 255, 255));
        lblExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblExit.setText("Exit");
        lblExit.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblExit.setMaximumSize(new java.awt.Dimension(130, 25));
        lblExit.setMinimumSize(new java.awt.Dimension(130, 25));
        lblExit.setOpaque(true);
        lblExit.setPreferredSize(new java.awt.Dimension(130, 25));
        lblExit.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                lblExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                lblExitMouseExited(evt);
            }
        });

        lblConnect.setBackground(new java.awt.Color(0, 0, 153));
        lblConnect.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        lblConnect.setForeground(new java.awt.Color(255, 255, 255));
        lblConnect.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblConnect.setText("Connect To Game Server");
        lblConnect.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        lblConnect.setMaximumSize(new java.awt.Dimension(130, 25));
        lblConnect.setMinimumSize(new java.awt.Dimension(130, 25));
        lblConnect.setOpaque(true);
        lblConnect.setPreferredSize(new java.awt.Dimension(130, 25));
        lblConnect.addMouseListener(new java.awt.event.MouseAdapter()
        {
            public void mouseClicked(java.awt.event.MouseEvent evt)
            {
                lblConnectMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt)
            {
                lblConnectMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt)
            {
                lblConnectMouseExited(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(lblMainImage, javax.swing.GroupLayout.PREFERRED_SIZE, 400, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(lblConnect, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(lblStartGameServer, javax.swing.GroupLayout.DEFAULT_SIZE, 300, Short.MAX_VALUE)
                    .addComponent(lblExit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(lblMainImage, javax.swing.GroupLayout.PREFERRED_SIZE, 140, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblStartGameServer, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblConnect, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblExit, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void lblExitMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblExitMouseClicked
    {//GEN-HEADEREND:event_lblExitMouseClicked
        System.exit(1);
    }//GEN-LAST:event_lblExitMouseClicked

    private void lblStartGameServerMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblStartGameServerMouseEntered
    {//GEN-HEADEREND:event_lblStartGameServerMouseEntered
        lblStartGameServer.setBackground(lblStartGameServer.getBackground().darker());
    }//GEN-LAST:event_lblStartGameServerMouseEntered

    private void lblConnectMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblConnectMouseEntered
    {//GEN-HEADEREND:event_lblConnectMouseEntered
        lblConnect.setBackground(lblConnect.getBackground().darker());
    }//GEN-LAST:event_lblConnectMouseEntered

    private void lblExitMouseEntered(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblExitMouseEntered
    {//GEN-HEADEREND:event_lblExitMouseEntered
        lblExit.setBackground(lblExit.getBackground().darker());
    }//GEN-LAST:event_lblExitMouseEntered

    private void lblStartGameServerMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblStartGameServerMouseExited
    {//GEN-HEADEREND:event_lblStartGameServerMouseExited
        lblStartGameServer.setBackground(lblStartGameServer.getBackground().brighter());
    }//GEN-LAST:event_lblStartGameServerMouseExited

    private void lblConnectMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblConnectMouseExited
    {//GEN-HEADEREND:event_lblConnectMouseExited
        lblConnect.setBackground(lblConnect.getBackground().brighter());
    }//GEN-LAST:event_lblConnectMouseExited

    private void lblExitMouseExited(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblExitMouseExited
    {//GEN-HEADEREND:event_lblExitMouseExited
        lblExit.setBackground(lblExit.getBackground().brighter());
    }//GEN-LAST:event_lblExitMouseExited

    private void lblStartGameServerMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblStartGameServerMouseClicked
    {//GEN-HEADEREND:event_lblStartGameServerMouseClicked
        gameServerUI.setSize(this.getSize());
        gameServerUI.setLocation(this.getLocation());
        gameServerUI.clearData();
        gameServerUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblStartGameServerMouseClicked

    private void lblConnectMouseClicked(java.awt.event.MouseEvent evt)//GEN-FIRST:event_lblConnectMouseClicked
    {//GEN-HEADEREND:event_lblConnectMouseClicked
        gameClientUI.setSize(this.getSize());
        gameClientUI.setLocation(this.getLocation());
        gameClientUI.clearData();
        gameClientUI.setVisible(true);
        this.setVisible(false);
    }//GEN-LAST:event_lblConnectMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[])
    {
        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable()
        {
            public void run()
            {
                new MainMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel lblConnect;
    private javax.swing.JLabel lblExit;
    private javax.swing.JLabel lblMainImage;
    private javax.swing.JLabel lblStartGameServer;
    // End of variables declaration//GEN-END:variables
}
